// GENERATED from the F# EditorEvent union (src/engine/FormaStudio.Engine/EditorEvent.fs).
// Do not edit. Regenerate with:
//   FORMA_STUDIO_UPDATE_GENERATED=1 dotnet run --project tests/FormaStudio.Engine.Tests -c Release
// Every semantic event the Studio engine handles, by wire name (forma-studio#18).
export const editorEvents = Object.freeze({
  select: "select", // Canvas
  clearSelection: "clear-selection", // Canvas
  toggleSelect: "toggle-select", // Canvas
  connectStart: "connect-start", // Canvas
  cancel: "cancel", // Canvas
  chooseKind: "choose-kind", // Canvas
  addNode: "add-node", // Canvas
  setLabel: "set-label", // Canvas
  delete: "delete", // Canvas
  moveLeft: "move-left", // Canvas
  moveRight: "move-right", // Canvas
  moveUp: "move-up", // Canvas
  moveDown: "move-down", // Canvas
  gestureMove: "gesture-move", // Canvas
  gestureResize: "gesture-resize", // Canvas
  setWidth: "set-width", // Canvas
  setHeight: "set-height", // Canvas
  reconnectEnd: "reconnect-end", // Canvas
  gestureReconnect: "gesture-reconnect", // Canvas
  zoomIn: "zoom-in", // Canvas
  zoomOut: "zoom-out", // Canvas
  zoomReset: "zoom-reset", // Canvas
  toggleSnap: "toggle-snap", // Canvas
  alignLeft: "align-left", // Canvas
  alignTop: "align-top", // Canvas
  distributeHorizontally: "distribute-horizontally", // Canvas
  copySelection: "copy-selection", // Templates
  chooseTemplate: "choose-template", // Templates
  insertTemplate: "insert-template", // Templates
  undo: "undo", // History
  redo: "redo", // History
  chooseField: "choose-field", // Inspector
  setFieldValue: "set-field-value", // Inspector
  setFieldOption: "set-field-option", // Inspector
  setFieldUnknown: "set-field-unknown", // Inspector
  clearField: "clear-field", // Inspector
  setFill: "set-fill", // Inspector
  chooseFillPalette: "choose-fill-palette", // Inspector
  resetFill: "reset-fill", // Inspector
  chooseStyle: "choose-style", // Inspector
  mappingValue: "mapping-value", // Inspector
  mappingSlot: "mapping-slot", // Inspector
  createMappingRule: "create-mapping-rule", // Inspector
  assignLane: "assign-lane", // Inspector
  draftFieldName: "draft-field-name", // Definitions
  draftFieldType: "draft-field-type", // Definitions
  draftFieldOptions: "draft-field-options", // Definitions
  draftFieldScope: "draft-field-scope", // Definitions
  createField: "create-field", // Definitions
  draftSlotName: "draft-slot-name", // Definitions
  draftSlotColor: "draft-slot-color", // Definitions
  createSlot: "create-slot", // Definitions
  deleteSlot: "delete-slot", // Definitions
  materializeSlot: "materialize-slot", // Definitions
  addPage: "add-page", // Layout
  openPage: "open-page", // Layout
  openDiagram: "open-diagram", // Layout
  layoutAddHeading: "layout-add-heading", // Layout
  layoutSetText: "layout-set-text", // Layout
  layoutTarget: "layout-target", // Layout
  layoutAddComponent: "layout-add-component", // Layout
  layoutMoveUp: "layout-move-up", // Layout
  layoutMoveDown: "layout-move-down", // Layout
  layoutDensity: "layout-density", // Layout
  openWorkflows: "open-workflows", // Workflows
  workflowNew: "workflow-new", // Workflows
  workflowOpened: "workflow-opened", // Workflows
  workflowChanged: "workflow-changed", // Workflows
  workflowSelect: "workflow-select", // Workflows
  workflowClose: "workflow-close", // Workflows
  workflowSave: "workflow-save", // Workflows
  workflowLoad: "workflow-load", // Workflows
  exportTarget: "export-target", // Export
  exportInteractive: "export-interactive", // Export
  exportBrand: "export-brand", // Export
  exportPage: "export-page", // Export
  exportComponent: "export-component", // Export
  exportWorkflow: "export-workflow", // Export
  copyExport: "copy-export", // Export
  save: "save", // Review
  load: "load", // Review
  checkSaved: "check-saved", // Review
  mergeTakeSaved: "merge-take-saved", // Review
  mergeKeepMine: "merge-keep-mine", // Review
  mergeCancel: "merge-cancel", // Review
  mergeApply: "merge-apply", // Review
  iconPick: "icon-pick", // Icons
  iconSearch: "icon-search", // Icons
  iconChoose: "icon-choose", // Icons
  iconClear: "icon-clear", // Icons
  iconCopy: "icon-copy", // Icons
  iconClose: "icon-close", // Icons
});
